### PR TITLE
Updated to support Asterisk 13.9.1

### PR DESCRIPTION
**Pull request by darrensessions**

### CODE REVIEW

**Comment by Marquis42** [comment]
Does the current code work if you just append /ari/events to the WebSocketURL config parameter?  If not, I'd rather fix that than to make a change which will break go-ari-proxy on older releases of Asterisk.  If so, then my recommendation would indeed be to just change configuration and possibly update the README.md to reflect the necessity of doing so for later Asterisk releases.

**Comment by darrensessions** [comment]
Looks like maybe there is more to it . . I've had to make a few other changes as well on the code level.

Let me change the URL and get back to you asap

**Comment by leifmadsen** [comment]
Any updates on this? :)

I do not think ASAP means what you think it means :D

**Comment by leifmadsen** [comment]
@darrensessions @Marquis42 I'm closing out this PR since it looks like there is no activity, and that the approach wasn't really approved. Thanks!

**Pull request closed without merging**
